name: suit_media_test
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  freezed: ^2.4.6
  freezed_annotation: ^2.4.1
  google_fonts: ^6.1.0
  http: ^1.1.2

dev_dependencies:
  build_runner: ^2.4.7
  flutter_gen_runner: ^5.3.2

  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/
  uses-material-design: true

flutter_gen:
  output: lib/core/assets/
